# Author: Axel Napolitano
# License: PolyForm-Noncommercial-1.0.0
# Funding links shown by GitHub in the repository sidebar.
# Current support channels: GitHub Sponsors and Ko-fi.
github: napolitano
ko_fi: X8X21EOLQ9
