# Author: Axel Napolitano
# License: PolyForm-Noncommercial-1.0.0
# Funding links shown by GitHub in the repository sidebar.
# Keep the GitHub Sponsors account and Patreon creator slug in sync with
# the canonical South Signal Lab project identity.
github: napolitano
patreon: southsignallab
