/**
 * @file external_sync_controller.h
 * @brief Deterministic scheduler-side processing for two configurable comparator inputs.
 * @author Axel Napolitano
 * @copyright 2026 Axel Napolitano
 * @license PolyForm-Noncommercial-1.0.0
 */
#pragma once

#include <cstdint>

#include "domain/clock_types.h"
#include "engine/clock_engine.h"
#include "hal/external_input_capture.h"

namespace clockfw::services {

/**
 * @brief Converts the two conditioned comparator inputs into configured musical roles.
 *
 * The physical PA8/PA9 paths remain the existing SYNC/RST hardware nets, but their
 * semantic roles are global firmware assignments. EXTI callbacks only enqueue
 * timestamped edges; all role interpretation and engine mutation happens at the
 * deterministic scheduler boundary.
 */
class ExternalSyncController final {
public:
    /** @brief Binds the conditioned input capture to the clock engine. */
    ExternalSyncController(
        hal::ExternalInputCapture& inputCapture,
        engine::ClockEngine& engine);

    /** @brief Initializes input interpretation from the persisted clock state. */
    void begin(const ClockState& state);
    /** @brief Publishes changed input/timing configuration to scheduler context. */
    void updateConfiguration(const ClockState& state);
    /** @brief Interprets queued comparator activity at one scheduler boundary. */
    void processSchedulerTick(std::uint32_t nowUs);
    /** @brief Clears estimator lock and returns to acquisition state. */
    void clearExternalLock();
    /** @brief Returns the current filtered external tempo in milli-BPM. */
    std::uint32_t filteredBpmMilli() const;
    /** @brief Records a front-panel transport action for external auto-start policy. */
    void notifyManualTransportState(TransportState transport);
    /** @brief Consumes one transport transition requested by an assigned input. */
    bool consumeTransportTransition(TransportState& transport);

    /**
     * @brief Consumes one TAP request generated by an assigned external input.
     * @param timestampUs Exact captured rising-edge timestamp.
     */
    bool consumeTapRequest(std::uint32_t& timestampUs);

private:
    /** @brief Processes the input assigned to RESET. */
    void processResetEdges();
    /** @brief Processes the input assigned to SYNC. */
    void processSyncEdges();
    /** @brief Processes one edge-triggered transport/input role. */
    void processTransportEdge(InputFunction function);
    /** @brief Applies level-authoritative RUN semantics. */
    void processRunLevel();
    /** @brief Discards activity for OFF and reserved roles. */
    void drainInactiveInputs();
    /** @brief Applies role changes safely at scheduler boundary. */
    void applyInputConfiguration();

    /** @brief Returns the physical input index assigned to a role, or -1. */
    int assignedInput(InputFunction function) const;
    /** @brief Pops one queued edge from a physical comparator input. */
    bool popInputEdge(int inputIndex, hal::ExternalInputEdge& edge);
    /** @brief Returns the conditioned current level of a physical input. */
    bool inputLevelHigh(int inputIndex) const;
    /** @brief Discards all queued edges from one physical input. */
    void drainInput(int inputIndex);

    /** @brief Returns whether a comparator level is the configured SYNC edge. */
    bool selectedSyncEdge(bool high) const;
    /** @brief Converts one accepted external period to milli-BPM. */
    std::uint32_t calculateBpmMilli(std::uint32_t periodUs) const;
    /** @brief Returns the adaptive external-clock timeout in microseconds. */
    std::uint32_t effectiveTimeoutUs() const;
    /** @brief Releases external lock and applies the configured loss policy. */
    void loseExternalLockFromIsr();
    /** @brief Applies auto-start policy when a valid external lock is acquired. */
    void startOnLockAcquisitionFromIsr();
    /** @brief Starts transport from an external role. */
    void requestPlayFromInput();
    /** @brief Stops transport from an external role. */
    void requestStopFromInput();
    /** @brief Performs deterministic stop-to-play restart from an external role. */
    void requestRestartFromInput();

    hal::ExternalInputCapture& inputCapture_;
    engine::ClockEngine& engine_;

    ExternalSyncSettings foregroundSettings_{};
    ExternalInputAssignments foregroundInputs_{};
    std::uint32_t foregroundFallbackBpmMilli_ = 120000U;
    std::uint16_t foregroundMinimumBpm_ = 20U;
    ClockSource foregroundSource_ = ClockSource::Auto;

    ExternalSyncSettings settings_{};
    ExternalInputAssignments inputs_{};
    std::uint32_t fallbackBpmMilli_ = 120000U;
    std::uint16_t minimumBpm_ = 20U;
    ClockSource source_ = ClockSource::Auto;

    bool configurationDirty_ = false;
    bool inputRolesChanged_ = false;
    bool resetGateApplied_ = false;
    bool runLevelInitialized_ = false;
    bool runLevelApplied_ = false;

    bool haveAcceptedPulse_ = false;
    bool externalLocked_ = false;
    std::uint32_t lastAcceptedPulseUs_ = 0U;
    std::uint64_t filteredPeriodQ8_ = 0U;
    std::uint32_t filteredBpmMilli_ = 0U;

    bool autoTransportArmed_ = true;
    volatile std::uint8_t pendingTransportTransition_ = 0xFFU;
    volatile bool pendingTap_ = false;
    volatile std::uint32_t pendingTapTimestampUs_ = 0U;
};

}  // namespace clockfw::services
