/**
 * @file ui_text.h
 * @brief Centralized user-visible text catalog prepared for future localization.
 * @author Axel Napolitano
 * @copyright 2026 Axel Napolitano
 * @license PolyForm-Noncommercial-1.0.0
 *
 * All user-visible static firmware strings belong in this file. Rendering and
 * domain code reference TextId values instead of embedding literals. Future
 * translations can add another catalog without changing screen logic.
 */

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

#include "config.h"

namespace clockfw::text {

/** @brief Identifiers for every static user-visible firmware string. */
enum class TextId : std::uint16_t {
    FirmwareName,
    McuShort,
    ModeOffShort,
    ModeClockShort,
    ModeEuclidShort,
    ModeSequencerShort,
    ModeOffLong,
    ModeClockLong,
    ModeEuclidLong,
    ModeSequencerLong,
    ModeUnifiedLong,
    ModeDividerLong,
    ModeUnifiedShort,
    ModeDividerShort,
    SourceInternal,
    SourceExternal,
    SourceAuto,
    TransportPlay,
    TransportPause,
    TransportStop,
    SyncRise,
    SyncFall,
    SyncFree,
    SyncLow,
    SyncMedium,
    SyncFull,
    On,
    Off,
    Global,
    RootSettings,
    Master,
    Sync,
    Templates,
    Info,
    Reset,
    PhaseReset,
    FactoryReset,
    FactoryResetConfirm,
    EraseAllData,
    Channel,
    Rate,
    Tempo,
    MinimumTempo,
    MaximumTempo,
    Humanize,
    MeterBeats,
    MeterUnit,
    PreCount,
    Transport,
    Source,
    Ppqn,
    Edge,
    Loss,
    Filter,
    Smoothing,
    Timeout,
    Product,
    Firmware,
    Mcu,
    Engine,
    Build,
    Time,
    Mode,
    Swing,
    Probability,
    Gate,
    Phase,
    Mute,
    ModeConfig,
    Bank,
    BankPowers,
    BankIntegers,
    BankPrimes,
    DivideMultiply,
    PolyNumerator,
    PolyDenominator,
    Steps,
    Hits,
    Rotate,
    Editor,
    Length,
    Invert,
    Clear,
    FillAlternate,
    Copy,
    Paste,
    TemplateAllMaster,
    TemplateClockTree,
    TemplateDividers,
    TemplatePolyrhythm,
    TemplateEuclidKit,
    TemplateHybrid,
    Arrow,
    SwingPrefix,
    FirmwarePrefix,
    SequencePagePrefix,
    LengthPrefix,
    ChannelFormat,
    ChannelStatusFormat,
    MeterFormat,
    PercentFormat,
    MillisecondsFormat,
    MinutesFormat,
    MicrosecondsFormat,
    KilohertzFormat,
    ModeTitleFormat,
    SequenceHeaderFormat,
    SequenceFooterFormat,
    SwingValueFormat,
    FirmwareVersionFormat,
    MasterSummaryFormat,
    EuclidDetailFormat,
    SequencerDetailFormat,
    EuclidSummaryFormat,
    Preferences,
    Screensaver,
    ScreensaverFractal,
    ScreensaverOrbit,
    ScreensaverPlug,
    ScreensaverClock,
    ScreensaverHeartbeat,
    ScreensaverAcid,
    ScreensaverSpectrum,
    ScreensaverField,
    ScreensaverBlox,
    ScreensaverMatrix,
    ScreensaverCubeCover,
    ScreensaverMakeMusic,
    ScreensaverLabyrinth,
    ScreensaverStarfield,
    ScreensaverFireworks,
    ScreensaverNone,
    StartAfter,
    DimAfter,
    OffAfter,
    AutoSave,
    LoadPreset,
    SavePreset,
    Empty,
    SelectChannel,
    NamePreset,
    HoldToSave,
    Current,
    LoadPresetTitle,
    SavePresetTitle,
    PresetDefaultFormat,
    Author,
    License,
    Framework,
    CoreLicense,
    HalLicense,
    CmsisLicense,
    Font,
    FontLicense,
    AuthorName,
    FirmwareLicenseShort,
    FrameworkName,
    CubeLicenseShort,
    BsdShort,
    ApacheShort,
    FontName,
    OverwritePreset,
    Yes,
    No,
    PushNext,
    GameHeaderFormat,
    GameOver,
    TapRetry,
    BreakoutTapStart,
    Formula1StatusFormat,
    DrummerEdm,
    DrummerHouse,
    DrummerTechno,
    DrummerHipHop,
    DrummerTrap,
    DrummerPop,
    DrummerRock,
    DrummerBlues,
    DrummerFunk,
    DrummerReggae,
    DrummerSalsa,
    DrummerSamba,
    DrummerBossaNova,
    DrummerDnb,
    ArcadePixelRaidTitle,
    ArcadeFormula1Title,
    ArcadeBreakoutTitle,
    ArcadeEggJourneyTitle,
    ArcadeBeatknechtTitle,
    ArcadePixelRaidMarquee,
    ArcadeFormula1Marquee,
    ArcadeBreakoutMarquee,
    ArcadeEggJourneyMarquee,
    ArcadeBeatknechtMarquee,
    ArcadeTop100,
    ArcadeNewTop100,
    ArcadeNoScores,
    ArcadeStartHint,
    ArcadeRestartHint,
    ArcadeRankFormat,
    ArcadeRangeFormat,
    ArcadeScoreFormat,
    ArcadeBeatknechtHint,
    NewHighScore,
    ExitGame,
    ChangeMode,
    GlobalMode,
    UnifiedModeHint,
    DividerModeHint,
    Presets,
    Display,
    System,
    GeneralSettings,
    Diagnostics,
    Inputs,
    Outputs,
    ResetShort,
    ChannelSettings,
    Licenses,
    Updates,
    ResetInputMode,
    Trigger,
    GateInput,
    EncoderDirection,
    Normal,
    Reversed,
    Orientation,
    Degrees0,
    Degrees180,
    HighScores,
    ClearHighScores,
    Groove,
    GroovePreset,
    Amount,
    Pattern,
    Timing,
    Output,
    GroovePrefix,
    Hardware,
    Input1,
    Input2,
    InputConfig,
    Run,
    InputStart,
    InputStop,
    Restart,
    Tap,
    Fill,
    GrooveMenu,
    GrooveEditorTitle,
    Save,
    Load,
    Zoom,
    GrooveName,
    LoadGroove,
    SaveGroove,
    EmptyBracketed,
    Fit,
    OverwriteGroove,
    DiscardChanges,
    GrooveStoreUnavailable,
    CustomGrooveStatusFormat,
    ZoomFormat,
    Count
};

/** @brief Number of entries required in one complete language catalog. */
inline constexpr std::size_t kTextCount = static_cast<std::size_t>(TextId::Count);

/** Complete catalog type required for every supported UI language. */
using TextCatalog = std::array<const char*, kTextCount>;

/** English (United States) catalog shipped by the prerelease firmware. */
inline constexpr TextCatalog kEnglishUs{{
    "SSL CLOCK", "F401CC",
    "O", "C", "E", "S", "OFF", "CLOCK", "EUCLID", "SEQUENCER", "ONE CLOCK", "DIVIDER", "ONE", "DIV",
    "INT", "EXT", "AUTO", "PLAY", "PAUSE", "STOP",
    "RISE", "FALL", "FREE", "LOW", "MEDIUM", "FULL", "ON", "OFF", "GLOBAL",
    "SETTINGS", "MASTER", "SYNC", "TEMPLATES", "INFO", "RESET", "PHASE RESET", "FACTORY RESET", "FACTORY RESET?", "ERASE ALL DATA",
    "CHANNEL", "RATE", "TEMPO", "MIN BPM", "MAX BPM", "HUMANIZE", "METER BEATS", "METER UNIT", "PRE COUNT", "TRANSPORT",
    "SOURCE", "PPQN", "EDGE", "LOSS", "FILTER", "SMOOTHING", "TIMEOUT",
    "NAME", "VERSION", "MCU", "ENGINE", "BUILD", "TIME",
    "MODE", "SWING", "PROB", "GATE", "PHASE", "MUTE", "MODE CFG",
    "BANK", "POW2", "INTEGER", "PRIME", "DIV/MULT", "POLY N", "POLY D", "STEPS", "HITS", "ROTATE", "EDITOR",
    "LENGTH", "INVERT", "CLEAR", "FILL ALT", "COPY", "PASTE",
    "ALL MASTER", "CLOCK TREE", "DIVIDERS", "POLYRHYTHM", "EUCLID KIT", "HYBRID",
    ">", "SW", "FW", "S", "LEN",
    "CH%u", "CH%u %c", "%u/%u", "%u%%", "%ums", "%umin", "%uus", "%lukHz",
    "CH%u MODE", "CH%u SEQ %u/4", "S%02u LEN%u", "SW %u%%", "%s",
    "%u %u/%u", "%u/%u R%u", "%u/64", "%u/%u",
    "PREFERENCES", "SCREENSAVER", "FRACTAL", "ORBIT", "PLUG", "CLOCK", "HEARTBEAT", "ACID", "SPECTRUM", "FIELD", "BLOX", "MATRIX", "CUBE COVER", "MAKE MUSIC", "LABYRINTH", "STARFIELD", "FIREWORKS", "OFF", "START", "DIM", "OFF", "AUTO SAVE", "LOAD PRESET", "SAVE PRESET", "EMPTY",
    "SELECT CHANNEL", "NAME PRESET", "HOLD TO SAVE", "CURRENT",
    "LOAD PRESET", "SAVE PRESET", "PRESET %u",
    "AUTHOR", "FIRMWARE", "FWK", "CORE LIC", "HAL LIC", "CMSIS", "FONT", "FONT LIC",
    "AXEL NAPOLITANO", "POLYFORM NC", "STM32CUBE F4", "BSD-3-CLAUSE", "BSD-3-CLAUSE", "APACHE-2.0",
    "ROBOTO COND", "OVERWRITE?", "YES", "NO", "PUSH NEXT",
    "S%lu HI%lu L%u", "GAME OVER", "TAP RETRY", "TAP START", "F1 %03u %05lu", "EDM", "HOUSE", "TECHNO", "HIP HOP", "TRAP", "POP", "ROCK", "BLUES", "FUNK", "REGGAE", "SALSA", "SAMBA", "BOSSA NOVA", "DNB",
    "PIXEL RAID", "FORMULA 1", "BREAKOUT", "EGG JOURNEY", "BEATKNECHT",
    "ALIENS CLOCKED IN. DEFEND THE GRID.", "LIGHTS OUT. KEEP IT BETWEEN THE LINES.", "BRICKS UP. BALL READY.", "THREE SHELLS. ONE VERY BAD MOON.", "NO DRUMMER? FINE. 8 GATES REPORTING FOR DUTY.",
    "TOP 100", "NEW TOP 100", "NO SCORES YET", "TAP/PUSH START", "BACK NEW GAME", "%02u %s %06lu", "%u-%u/%u", "SCORE %lu", "PLAY START",
    "NEW HIGH SCORE", "EXIT GAME?",
    "CHANGE MODE?", "GLOBAL MODE", "ONE CLOCK / 8 OUTS", "FIXED DIVIDER BANK",
    "PRESETS", "DISPLAY", "SYSTEM", "GENERAL SETTINGS", "DIAGNOSTICS", "INPUTS", "OUTPUTS", "RST", "CHANNEL SETTINGS", "LICENSES", "UPDATES",
    "RST MODE", "TRIGGER", "GATE",
    "ENCODER DIR", "NORMAL", "REVERSED", "ORIENTATION", "0 DEG", "180 DEG",
    "HI-SCORES", "CLEAR HI-SCORES?", "GROOVE", "PRESET", "AMOUNT", "PATTERN", "TIMING", "OUTPUT", "G:",
    "HARDWARE", "INPUT 1", "INPUT 2", "CONFIG", "RUN", "START", "STOP", "RESTART", "TAP", "FILL",
    "GROOVE MENU", "GROOVE EDITOR", "SAVE", "LOAD", "ZOOM", "GROOVE NAME", "LOAD GROOVE", "SAVE GROOVE", "<EMPTY>", "FIT",
    "OVERWRITE GROOVE?", "DISCARD CHANGES?", "GROOVE STORE N/A", "S%02u %+d  L%u", "Z%u"
}};

/**
 * @brief Resolves a complete language catalog.
 * @param language Requested UI language.
 * @return Complete catalog, falling back atomically to en-US when unavailable.
 */
const TextCatalog& catalogFor(config::UiLanguage language);

/**
 * @brief Returns one localized UI string.
 * @param id Stable string identifier used by the UI or domain layer.
 * @param language Requested language catalog.
 * @return Null-terminated localized text. Unsupported languages fall back to en-US.
 */
const char* get(
    TextId id,
    config::UiLanguage language = config::kUiLanguage);

}  // namespace clockfw::text
